name: buildProject

on: 
  push:
     branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.15.x'

    - name: Install dependencies
      run: npm install
    - name: create test
      run: echo "Commit Message 1" >> commit_message.txt
      
    - name: Build Angular project
      run: npm run build
      
    - name: List files
      run: ls  
      
    - name: commit-push
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Automated Change
          commit_user_name: kelly103312
          commit_user_email: cristaldemilcolores@gmail.com
          
    - name: "Run if changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: echo "Changes!"

    - name: "Run if no changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: echo "No Changes!"
