name: buildProject

on: 
  push:
     branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/node@v4
        with:
            node-version: '13.2.0'
            
      - run: npm install

      - run: ng build

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/Udemy-angular
          enable_jekyll: true 
