name: buildProject

on: 
  push:
     branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/node@v4
        with:
            node-version: '13.2.0'
            
      - run: npm install

      - run: ng build

